# Generated by Django 3.2 on 2021-05-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('standings', models.CharField(max_length=2)),
                ('wins', models.CharField(max_length=3)),
                ('draws', models.CharField(max_length=3)),
                ('losses', models.CharField(max_length=3)),
            ],
        ),
    ]
